/*eslint-disable*/
export const CREATE_LIVRAISON = 'CREATE_LIVRAISON';
export const UPDATE_LIVRAISON = 'UPDATE_LIVRAISON';
export const DELETE_LIVRAISON = 'DELETE_LIVRAISON';
export const END = 'END';
export const START = 'START';

// export const LIVRAISON_CREATE_REQUEST = 'LIVRAISON_CREATE_REQUEST'
// export const LIVRAISON_CREATE_SUCCESS = 'LIVRAISON_CREATE_SUCCESS'
// export const LIVRAISON_CREATE_FAIL = 'LIVRAISON_CREATE_FAIL'
// export const LIVRAISON_CREATE_RESET = 'LIVRAISON_CREATE_RESET'

export const FETCH_ALL_LIVRAISON ='FETCH_ALL_LIVRAISON'
export const FETCH_LIVRAISON ='FETCH_LIVRAISON'