/*eslint-disable*/
export const UPDATE_MAGASINIER= 'UPDATE_MAGASINIER'
export const DELETE_MAGASINIER ='DELETE_MAGASINIER'
export const CREATE_MAGASINIER = 'CREATE_MAGASINIER'

export const AUTH_MAGASINIER = 'AUTH_MAGASINIER';
export const LOGOUT_MAGASINIER = 'LOGOUT_MAGASINIER';
