/*eslint-disable*/
export const GET_PRODUITS_REQUEST =" GET_PRODUITS_REQUEST"
export const GET_PRODUITS_SUCCESS =" GET_PRODUITS_SUCCESS"
export const GET_PRODUITS_FAIL =" GET_PRODUITS_FAIL"
export const UPDATE_PRODUIT ="UPDATE_PRODUIT"

export const GET_PRODUIT_DETAILS_REQUEST =" GET_PRODUIT_DETAILS_REQUEST"
export const GET_PRODUIT_DETAILS_SUCCESS =" GET_PRODUIT_DETAILS_SUCCESS"
export const GET_PRODUIT_DETAILS_FAIL =" GET_PRODUIT_DETAILS_FAIL"
export const GET_PRODUIT_DETAILS_RESET =" GET_PRODUIT_DETAILS_RESET"
